import type { IdolGroup, IdolMember, News, BoardPost, Board } from '@/types'

export const dummyGroups: IdolGroup[] = [
  {
    id: '1',
    name: 'STARLET☆RIOT',
    description: '東京発、パワフルなパフォーマンスで話題沸騰中のガールズアイドルグループ。メンバー5人が奏でるライブは圧巻のクオリティ。',
    image_url: 'https://picsum.photos/seed/group1/400/400',
    agency: 'スターライトプロ',
    area: '東京',
    genre: 'パフォーマンス系',
    formed_year: 2021,
    official_x_url: 'https://x.com',
    official_instagram_url: null,
    official_tiktok_url: null,
    official_website_url: null,
    created_at: '2024-01-01',
    member_count: 5,
  },
  {
    id: '2',
    name: 'ゆめかわ☆パレード',
    description: 'ゆめかわいいをコンセプトに活動するアイドルグループ。メルヘンな世界観とキャッチーな楽曲が人気。',
    image_url: 'https://picsum.photos/seed/group2/400/400',
    agency: 'ドリームワークス',
    area: '大阪',
    genre: 'ゆめかわ系',
    formed_year: 2020,
    official_x_url: null,
    official_instagram_url: 'https://instagram.com',
    official_tiktok_url: 'https://tiktok.com',
    official_website_url: 'https://example.com',
    created_at: '2024-01-01',
    member_count: 6,
  },
  {
    id: '3',
    name: 'NEON BLADE',
    description: 'ダークでエッジの効いたビジュアルとヘビーなサウンドが特徴のロック系アイドルグループ。',
    image_url: 'https://picsum.photos/seed/group3/400/400',
    agency: 'ネオンレーベル',
    area: '名古屋',
    genre: 'ロック系',
    formed_year: 2022,
    official_x_url: 'https://x.com',
    official_instagram_url: null,
    official_tiktok_url: null,
    official_website_url: null,
    created_at: '2024-01-01',
    member_count: 4,
  },
  {
    id: '4',
    name: 'プリズム★プリンセス',
    description: '王道アイドルポップを追求する正統派アイドルグループ。握手会やチェキ会も積極的に開催中。',
    image_url: 'https://picsum.photos/seed/group4/400/400',
    agency: 'プリズムエンタメ',
    area: '東京',
    genre: '王道アイドル',
    formed_year: 2019,
    official_x_url: 'https://x.com',
    official_instagram_url: 'https://instagram.com',
    official_tiktok_url: null,
    official_website_url: 'https://example.com',
    created_at: '2024-01-01',
    member_count: 7,
  },
  {
    id: '5',
    name: 'アキバ電波隊',
    description: 'アキバカルチャー全開のアニソン系アイドルグループ。コスプレやアニメコラボも多数実施。',
    image_url: 'https://picsum.photos/seed/group5/400/400',
    agency: 'アキバプロ',
    area: '東京',
    genre: '電波系',
    formed_year: 2018,
    official_x_url: 'https://x.com',
    official_instagram_url: null,
    official_tiktok_url: 'https://tiktok.com',
    official_website_url: null,
    created_at: '2024-01-01',
    member_count: 8,
  },
  {
    id: '6',
    name: 'サクラメン地下鉄道',
    description: '独自の世界観と哲学的な歌詞が特徴のアンダーグラウンドアイドル。',
    image_url: 'https://picsum.photos/seed/group6/400/400',
    agency: 'インディーズ',
    area: '福岡',
    genre: 'アングラ系',
    formed_year: 2023,
    official_x_url: null,
    official_instagram_url: 'https://instagram.com',
    official_tiktok_url: null,
    official_website_url: null,
    created_at: '2024-01-01',
    member_count: 3,
  },
]

export const dummyMembers: IdolMember[] = [
  {
    id: '1',
    group_id: '1',
    name: '桜井ひなた',
    image_url: 'https://picsum.photos/seed/member1/400/400',
    color: '#FF69B4',
    birthday: '2002-03-15',
    birthplace: '東京都',
    profile: 'STARLET☆RIOTのリーダー。ダンスが得意で振り付けも担当。趣味は映画鑑賞とカフェ巡り。好きな食べ物はいちごパフェ。',
    joined_at: '2021-04-01',
    graduated_at: null,
    official_x_url: 'https://x.com',
    official_instagram_url: null,
    official_tiktok_url: null,
    created_at: '2024-01-01',
    group: dummyGroups[0],
  },
  {
    id: '2',
    group_id: '1',
    name: '月島りの',
    image_url: 'https://picsum.photos/seed/member2/400/400',
    color: '#9B59B6',
    birthday: '2003-07-22',
    birthplace: '神奈川県',
    profile: 'グループ最年少。透き通るような歌声が自慢。アニメとゲームが大好きなオタク系アイドル。',
    joined_at: '2021-04-01',
    graduated_at: null,
    official_x_url: null,
    official_instagram_url: 'https://instagram.com',
    official_tiktok_url: 'https://tiktok.com',
    created_at: '2024-01-01',
    group: dummyGroups[0],
  },
  {
    id: '3',
    group_id: '1',
    name: '星野あおい',
    image_url: 'https://picsum.photos/seed/member3/400/400',
    color: '#3498DB',
    birthday: '2001-11-08',
    birthplace: '埼玉県',
    profile: 'ラップとDJを担当する個性派メンバー。音楽制作にも挑戦中。趣味は音楽フェス巡り。',
    joined_at: '2021-06-15',
    graduated_at: null,
    official_x_url: 'https://x.com',
    official_instagram_url: null,
    official_tiktok_url: null,
    created_at: '2024-01-01',
    group: dummyGroups[0],
  },
  {
    id: '4',
    group_id: '2',
    name: '花咲まりん',
    image_url: 'https://picsum.photos/seed/member4/400/400',
    color: '#FF85C0',
    birthday: '2004-02-14',
    birthplace: '大阪府',
    profile: 'ゆめかわ☆パレードの看板娘。かわいいものが大好きで、ファッションもゆめかわスタイル。',
    joined_at: '2020-07-01',
    graduated_at: null,
    official_x_url: null,
    official_instagram_url: 'https://instagram.com',
    official_tiktok_url: null,
    created_at: '2024-01-01',
    group: dummyGroups[1],
  },
  {
    id: '5',
    group_id: '3',
    name: '黒羽しずく',
    image_url: 'https://picsum.photos/seed/member5/400/400',
    color: '#2C3E50',
    birthday: '2000-09-30',
    birthplace: '愛知県',
    profile: 'NEON BLADEのボーカル&ギタリスト。音楽学校出身のガチ勢。ハードロックへの愛が深い。',
    joined_at: '2022-01-10',
    graduated_at: null,
    official_x_url: 'https://x.com',
    official_instagram_url: null,
    official_tiktok_url: null,
    created_at: '2024-01-01',
    group: dummyGroups[2],
  },
]

export const dummyNews: News[] = [
  {
    id: '1',
    title: 'STARLET☆RIOT、初の武道館ライブ開催決定！',
    body: `STARLET☆RIOTが、2025年8月15日に日本武道館にてワンマンライブ「STARLET☆RIOT BUDOKAN 2025」を開催することが決定しました。

チケットは5月1日より一般発売開始。ファンクラブ先行は4月15日より受付開始予定です。

リーダーの桜井ひなたはコメントを寄せ、「ずっと夢だった武道館に立てることが信じられません。応援してくれるみんなのおかげです。絶対に最高のライブにします！」と喜びを語りました。`,
    thumbnail_url: 'https://picsum.photos/seed/news1/600/400',
    category: 'live',
    source_url: 'https://example.com/news/1',
    group_id: '1',
    member_id: null,
    created_at: '2025-04-20T10:00:00Z',
    group: dummyGroups[0],
  },
  {
    id: '2',
    title: 'ゆめかわ☆パレード、新曲「ドリームランドへようこそ」MV公開',
    body: `ゆめかわ☆パレードが新曲「ドリームランドへようこそ」のミュージックビデオを公開しました。

ファンタジックな世界観で撮影されたMVは、公開から24時間で100万再生を突破。SNS上でも大きな話題を呼んでいます。

楽曲は5月10日にデジタルリリース予定。CDシングルは6月発売の予定です。`,
    thumbnail_url: 'https://picsum.photos/seed/news2/600/400',
    category: 'release',
    source_url: 'https://example.com/news/2',
    group_id: '2',
    member_id: null,
    created_at: '2025-04-18T14:30:00Z',
    group: dummyGroups[1],
  },
  {
    id: '3',
    title: 'NEON BLADE、新メンバー加入を発表',
    body: `NEON BLADEは、新メンバー「影山のえる」の加入を発表しました。

影山のえるは18歳で、ギターとボーカルを担当。高校時代からバンド活動を行っており、そのスキルが高く評価されての加入となりました。

加入お披露目ライブは5月3日、名古屋DIAMOND HALLにて開催予定です。`,
    thumbnail_url: 'https://picsum.photos/seed/news3/600/400',
    category: 'member',
    source_url: 'https://example.com/news/3',
    group_id: '3',
    member_id: null,
    created_at: '2025-04-15T09:00:00Z',
    group: dummyGroups[2],
  },
  {
    id: '4',
    title: 'プリズム★プリンセス、全国ツアー日程発表',
    body: `プリズム★プリンセスが2025年秋の全国ツアー「PRISM TOUR 2025 〜虹色の軌跡〜」の日程を発表しました。

東京・大阪・名古屋・福岡・札幌の5都市を回る大規模ツアーで、全10公演が予定されています。

チケット先行受付は5月1日よりオフィシャルサイトにて開始。`,
    thumbnail_url: 'https://picsum.photos/seed/news4/600/400',
    category: 'live',
    source_url: 'https://example.com/news/4',
    group_id: '4',
    member_id: null,
    created_at: '2025-04-12T11:00:00Z',
    group: dummyGroups[3],
  },
  {
    id: '5',
    title: 'アキバ電波隊、人気アニメとのコラボシングル決定',
    body: `アキバ電波隊が、TVアニメ「魔法少女☆ハッカー」のオープニングテーマを担当することが決定しました。

タイトルは「バイナリ☆マジック」で、7月クールの放送開始に合わせてリリース予定。

アニメの主人公をモデルにした衣装でのパフォーマンスも予定されており、ファンの期待が高まっています。`,
    thumbnail_url: 'https://picsum.photos/seed/news5/600/400',
    category: 'media',
    source_url: 'https://example.com/news/5',
    group_id: '5',
    member_id: null,
    created_at: '2025-04-10T16:00:00Z',
    group: dummyGroups[4],
  },
  {
    id: '6',
    title: '桜井ひなた、ソロ写真集「ひなたの春」発売決定',
    body: `STARLET☆RIOTのリーダー・桜井ひなたのソロ写真集「ひなたの春」が5月25日に発売決定！

春の自然の中で撮影されたナチュラルテイストな一冊。全128ページ、価格は3,300円（税込）。`,
    thumbnail_url: 'https://picsum.photos/seed/news6/600/400',
    category: 'release',
    source_url: 'https://example.com/news/6',
    group_id: '1',
    member_id: '1',
    created_at: '2025-04-08T12:00:00Z',
    group: dummyGroups[0],
    member: dummyMembers[0],
  },
]

export const dummyBoardPosts: BoardPost[] = [
  {
    id: '1',
    board_id: '1',
    user_id: 'u1',
    body: '昨日のライブ最高でした！ひなたちゃんのソロパートで泣いてしまった…次のライブも絶対行きます！',
    image_url: null,
    like_count: 42,
    parent_post_id: null,
    created_at: '2025-04-25T20:30:00Z',
    user: { id: 'u1', name: 'ひなた推し🌸', email: '', avatar_url: 'https://picsum.photos/seed/user1/100/100', bio: null, role: 'user', created_at: '' },
    replies: [
      {
        id: '1-1',
        board_id: '1',
        user_id: 'u2',
        body: 'わかります！あのソロ部分は本当に感動的でしたね。またライブで会いましょう！',
        image_url: null,
        like_count: 12,
        parent_post_id: '1',
        created_at: '2025-04-25T21:00:00Z',
        user: { id: 'u2', name: 'りの担当', email: '', avatar_url: 'https://picsum.photos/seed/user2/100/100', bio: null, role: 'user', created_at: '' },
      },
    ],
  },
  {
    id: '2',
    board_id: '1',
    user_id: 'u3',
    body: '武道館ライブのチケット当選しました！！！初日参戦します！どなたか一緒に行く方いますか？',
    image_url: null,
    like_count: 28,
    parent_post_id: null,
    created_at: '2025-04-24T15:00:00Z',
    user: { id: 'u3', name: 'あおいサイリウム', email: '', avatar_url: 'https://picsum.photos/seed/user3/100/100', bio: null, role: 'user', created_at: '' },
    replies: [],
  },
  {
    id: '3',
    board_id: '1',
    user_id: 'u4',
    body: '新曲の振り付け練習動画が公開されてた！みんなもう見た？メンバーのダンス上手すぎる',
    image_url: null,
    like_count: 35,
    parent_post_id: null,
    created_at: '2025-04-23T12:00:00Z',
    user: { id: 'u4', name: 'スタリオ大好き', email: '', avatar_url: 'https://picsum.photos/seed/user4/100/100', bio: null, role: 'user', created_at: '' },
    replies: [],
  },
  {
    id: '4',
    board_id: '1',
    user_id: 'u5',
    body: '今日のチェキ会でひなたちゃんに「ずっと応援してるよ」って伝えたら「ありがとう、これからもよろしくね！」って言ってくれて最高でした😭💖',
    image_url: null,
    like_count: 67,
    parent_post_id: null,
    created_at: '2025-04-22T18:30:00Z',
    user: { id: 'u5', name: 'ひなてゃ命', email: '', avatar_url: 'https://picsum.photos/seed/user5/100/100', bio: null, role: 'user', created_at: '' },
    replies: [],
  },
]

export const dummyBoards: Board[] = [
  { id: '1', type: 'group', group_id: '1', member_id: null, title: 'STARLET☆RIOT 掲示板', created_at: '2024-01-01', post_count: 234 },
  { id: '2', type: 'group', group_id: '2', member_id: null, title: 'ゆめかわ☆パレード 掲示板', created_at: '2024-01-01', post_count: 189 },
  { id: '3', type: 'member', group_id: '1', member_id: '1', title: '桜井ひなた 掲示板', created_at: '2024-01-01', post_count: 156 },
  { id: '4', type: 'member', group_id: '1', member_id: '2', title: '月島りの 掲示板', created_at: '2024-01-01', post_count: 143 },
]
